library(plyr)
nom = read.table("UCI HAR Dataset/features.txt", quote = " ")
activities = read.table("UCI HAR Dataset/activity_labels.txt", quote = " ")
x1 = read.table("UCI HAR Dataset/test/X_test.txt", quote = " ")
x2 = read.table("UCI HAR Dataset/test/subject_test.txt")
x3 = read.table("UCI HAR Dataset/test/y_test.txt")
y1 = read.table("UCI HAR Dataset/train/X_train.txt", quote = " ")
y2 = read.table("UCI HAR Dataset/train/subject_train.txt", quote = " ")
y3 = read.table("UCI HAR Dataset/train/y_train.txt", quote = " ")
X = cbind(x1, x2, x3)
Y = cbind(y1, y2, y3)
Z = rbind(X, Y)
names(Z) = c(as.character(nom[, 2]), "subject", "activity")
Z = mutate(Z, activity = factor(activity, levels = activities[, 1], labels = activities[, 2]))
mean.std = Z[, grepl("mean\\(", names(Z)) |  grepl("std\\(", names(Z))]
Z = c(mean.std, Z[, 562:563])
# respaldo = names(Z)
names(Z) = respaldo

names(Z) = gsub("Acc", ".Accelerometer", names(Z))
names(Z) = gsub("Gyro", ".Gyroscope", names(Z))
names(Z) = gsub("Body", ".Body", names(Z))
names(Z) = gsub("Gravity", ".Gravity", names(Z))
names(Z) = gsub("-mean", ".Mean", names(Z))
names(Z) = gsub("std", ".Standard.deviation", names(Z))
names(Z) = gsub("\\(|\\)|-", "", names(Z))
names(Z) = gsub("t[.]", "Time.", names(Z))
names(Z) = gsub("f[.]", "Frequency.", names(Z))
names(Z) = gsub("Mag", ".Magnitude", names(Z))
names(Z) = gsub("X", ".on.X", names(Z))
names(Z) = gsub("Y", ".on.Y", names(Z))
names(Z) = gsub("Z", ".on.Z", names(Z))
names(Z) = gsub("Jerk", ".Jerk", names(Z))
names(Z)

